# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rc.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 1600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 781, 771))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(6, 34, 371, 334))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ShiftConfig = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ShiftConfig.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ShiftConfig.setFont(font)
        self.ShiftConfig.setObjectName("ShiftConfig")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ShiftConfig)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.RunTypeConfig = QtWidgets.QComboBox(self.layoutWidget1)
        self.RunTypeConfig.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RunTypeConfig.setFont(font)
        self.RunTypeConfig.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.RunTypeConfig.setObjectName("RunTypeConfig")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.RunTypeConfig)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.RunDescConfig = QtWidgets.QTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RunDescConfig.setFont(font)
        self.RunDescConfig.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.RunDescConfig.setObjectName("RunDescConfig")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.RunDescConfig)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.SplitTimeConfig = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SplitTimeConfig.setFont(font)
        self.SplitTimeConfig.setObjectName("SplitTimeConfig")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SplitTimeConfig)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.ConfigFileButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.ConfigFileButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ConfigFileButton.setFont(font)
        self.ConfigFileButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConfigFileButton.setObjectName("ConfigFileButton")
        self.verticalLayout_2.addWidget(self.ConfigFileButton)
        self.ConfigFileLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ConfigFileLabel.setFont(font)
        self.ConfigFileLabel.setText("")
        self.ConfigFileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfigFileLabel.setObjectName("ConfigFileLabel")
        self.verticalLayout_2.addWidget(self.ConfigFileLabel)
        self.horizontalLayout.addWidget(self.groupBox)
        self.runControlBox = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.runControlBox.setFont(font)
        self.runControlBox.setAlignment(QtCore.Qt.AlignCenter)
        self.runControlBox.setObjectName("runControlBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.runControlBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 34, 361, 341))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BootButton = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BootButton.sizePolicy().hasHeightForWidth())
        self.BootButton.setSizePolicy(sizePolicy)
        self.BootButton.setMinimumSize(QtCore.QSize(0, 0))
        self.BootButton.setMaximumSize(QtCore.QSize(1000, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BootButton.setFont(font)
        self.BootButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BootButton.setObjectName("BootButton")
        self.verticalLayout.addWidget(self.BootButton)
        self.ConfigButton = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigButton.sizePolicy().hasHeightForWidth())
        self.ConfigButton.setSizePolicy(sizePolicy)
        self.ConfigButton.setMinimumSize(QtCore.QSize(0, 40))
        self.ConfigButton.setMaximumSize(QtCore.QSize(1000, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ConfigButton.setFont(font)
        self.ConfigButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConfigButton.setObjectName("ConfigButton")
        self.verticalLayout.addWidget(self.ConfigButton)
        self.StartButton = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        self.StartButton.setMinimumSize(QtCore.QSize(0, 40))
        self.StartButton.setMaximumSize(QtCore.QSize(1000, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.StartButton.setFont(font)
        self.StartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout.addWidget(self.StartButton)
        self.EndButton = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndButton.sizePolicy().hasHeightForWidth())
        self.EndButton.setSizePolicy(sizePolicy)
        self.EndButton.setMinimumSize(QtCore.QSize(0, 40))
        self.EndButton.setMaximumSize(QtCore.QSize(1000, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EndButton.setFont(font)
        self.EndButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EndButton.setObjectName("EndButton")
        self.verticalLayout.addWidget(self.EndButton)
        self.ExitButton = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitButton.sizePolicy().hasHeightForWidth())
        self.ExitButton.setSizePolicy(sizePolicy)
        self.ExitButton.setMinimumSize(QtCore.QSize(0, 40))
        self.ExitButton.setMaximumSize(QtCore.QSize(1000, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ExitButton.setFont(font)
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ExitButton.setObjectName("ExitButton")
        self.verticalLayout.addWidget(self.ExitButton)
        self.horizontalLayout.addWidget(self.runControlBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.RunStatsBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.RunStatsBox.setMaximumSize(QtCore.QSize(16777215, 381))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RunStatsBox.setFont(font)
        self.RunStatsBox.setAlignment(QtCore.Qt.AlignCenter)
        self.RunStatsBox.setObjectName("RunStatsBox")
        self.verticalLayout_3.addWidget(self.RunStatsBox)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(930, 20, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1340, 20, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.UpdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateButton.setGeometry(QtCore.QRect(1150, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UpdateButton.setFont(font)
        self.UpdateButton.setObjectName("UpdateButton")
        self.FADCFIG = QtWidgets.QLabel(self.centralwidget)
        self.FADCFIG.setGeometry(QtCore.QRect(810, 50, 381, 341))
        self.FADCFIG.setObjectName("FADCFIG")
        self.SADCFIG = QtWidgets.QLabel(self.centralwidget)
        self.SADCFIG.setGeometry(QtCore.QRect(1200, 50, 381, 341))
        self.SADCFIG.setObjectName("SADCFIG")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "rc"))
        self.groupBox.setTitle(_translate("MainWindow", "Run Configuration"))
        self.label.setText(_translate("MainWindow", "Shift"))
        self.label_2.setText(_translate("MainWindow", "Run Type"))
        self.label_3.setText(_translate("MainWindow", "Run Desc"))
        self.label_4.setText(_translate("MainWindow", "Split T[m]"))
        self.ConfigFileButton.setText(_translate("MainWindow", "Load Configuration File"))
        self.runControlBox.setTitle(_translate("MainWindow", "Run Control"))
        self.BootButton.setText(_translate("MainWindow", "Boot"))
        self.ConfigButton.setText(_translate("MainWindow", "Config Run"))
        self.StartButton.setText(_translate("MainWindow", "Start Run"))
        self.EndButton.setText(_translate("MainWindow", "End Run"))
        self.ExitButton.setText(_translate("MainWindow", "Exit"))
        self.RunStatsBox.setTitle(_translate("MainWindow", "Run Statistics"))
        self.label_5.setText(_translate("MainWindow", "FADC Waveforms"))
        self.label_6.setText(_translate("MainWindow", "SADC Waveforms"))
        self.UpdateButton.setText(_translate("MainWindow", "Update"))
        self.FADCFIG.setText(_translate("MainWindow", "Figure ..."))
        self.SADCFIG.setText(_translate("MainWindow", "Figure ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
